# Generated by Django 5.0.6 on 2024-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_civil_status_item_gender_item_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='GSIS_ID_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='PAGIBIG_ID_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(default='', max_length=100),
        ),
    ]
