# Generated by Django 5.0.6 on 2024-07-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_gsis_id_no_item_pagibig_id_no_item_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='PHILHEALTH_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='SSS_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='TIN_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='agency_employee_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(default='', max_length=100),
        ),
    ]
