# Generated by Django 5.0.6 on 2024-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_philhealth_no_item_sss_no_item_tin_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Fathers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='Mothers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='ZIP_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
